web21/models/gears.py
from sqlalchemy import *
from models import Base,Model_action
import time
#科学计算
import scipy as sci
import pandas as pd
#目录操作
import os



class Gears(Base, Model_action):
    """
    Model 是所有 model 的基类
    @classmethod 是一个套路用法
    例如
    user = User()
    user.db_path() 返回 User.txt
    """
    def __init__(self):
        self.path = "sqlite:///data/article.sqlite"
        self.base = Base

    __tablename__ = "Gears"
    id = Column(Integer, primary_key=True)
    gear_id = Column(Integer, default=0)
    gear_name = Column(String, default='')
    gear_pic = Column(String, default='')
    gear_url = Column(String, default='')
    gear_class = Column(String, default='')
    tbk_url = Column(String, default='')
    gear_price = Column(Float, default=0.00)
    gear_sales = Column(Integer, default=0)
    tbk_v_return = Column(Float, default=0.00)
    tbk_return = Column(Float, default=0.00)
    gear_saler = Column(String, default="")
    gear_plantform = Column(String, default="")
    coupon_id = Column(String, default="")
    coupon_num = Column(Integer, default=0)
    coupon_remain = Column(Integer, default=0)
    coupon_detail = Column(String, default="")
    coupon_begin = Column(String, default="")
    coupon_end = Column(String, default="")
    coupon_link = Column(String, default="")
    coupon_tbk_link = Column(String, default="")

    created_time =Column(Integer,default=0)
    updated_time =Column(Integer,default=0)

    @classmethod
    def new(cls, form, **kwargs):
        m = cls()
        for k, v in form.items():
            if k in cls.__dict__:
                setattr(m, k, v)

        for k, v in kwargs.items():
            # print(k)
            if hasattr(m, k):
                setattr(m, k, v)
            else:
                raise KeyError
        timestamp = int(time.time())
        m.created_time = timestamp
        m.updated_time = timestamp
        m.save()

        @classmethod
        def update(cls, form, id):
            session = cls.get_session()
            m = session.query(cls).filter_by(id=id).first()
            for k, v in form.items():
                if k in dir(cls):
                    setattr(m, k, v)
                    print(m)
                else:
                    raise KeyError
            timestamp = int(time.time())
            m.updated_time = timestamp
            session.commit()
            session.close()

    @classmethod
    def get_taobao_data(cls, filepath="data/taobao/taobao-2017-12-17.xks"):
        taobao_data = pd.read_excel(filepath, sheet_name=1)
        # i = 0
        index=taobao_data["商品id"]
        gear_form={}
        m= len(index)
        for x in range(0,m):
            # print(taobao_data.iloc[x,])
            items = taobao_data.iloc[x,]
            gear_form = {
                "gear_id": int(items["商品id"]),
                "gear_name": items["商品名称"],
                "gear_pic": items["商品主图"],
                "gear_url": items["商品详情页链接地址"],
                "gear_class": items["商品一级类目"],
                "tbk_url": items["淘宝客链接"],
                "gear_price": float(items["商品价格(单位：元)"]),
                "gear_sales": int(items["商品月销量"]),
                "tbk_v_return": float(items["收入比率(%)"]),
                "tbk_return": float(items["佣金"]),
                "gear_saler": items["卖家旺旺"],
                "gear_plantform": items["平台类型"],
                "coupon_id": items["优惠券id"],
                "coupon_num": int(items["优惠券总量"]),
                "coupon_remain": int(items["优惠券剩余量"]),
                "coupon_detail": items["优惠券面额"],
                "coupon_begin": items["优惠券开始时间"],
                "coupon_end": items["优惠券结束时间"],
                "coupon_link": items["优惠券链接"],
                "coupon_tbk_link": items["商品优惠券推广链接"],
            }
            cls.creat_sheet()
            cls.new(gear_form)

    @classmethod
    def tags_get(cls):
        m = cls.all()
        lis=[]
        list1=[]
        list2=[]
        list3=[]
        for x in m:
            n = x.gear_class.split("/")
            # print(n)
            try:
                if n[0]:
                    list1.append(n[0])
                if n[1]:
                    list2.append(n[1])
                if n[2]:
                    list3.append(n[2])
            except:
                pass
        list1=list(set(list1))
        list2=list(set(list2))
        list3=list(set(list3))
        print(list1,list2,list3)

web21/routes/gears.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
    abort,
)
from werkzeug.utils import secure_filename
import os
import uuid
import random
import json
import  time
import jieba

from models.gears import Gears
from routes import current_user
from utils import log
import operator


main = Blueprint('gears', __name__)


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():


    return render_template('gears/index.html')


@main.route("/search",methods=["GET"])
def search():
    form =  request.args.get('searchtext', '')
    words = form.split(" ")
    gear= Gears.find_words_in_article("gear_name",words)
    return render_template('gears/detail.html',gears = gear )




@main.route("/final")
def detail():
    list11 = []
    m = Gears().find_words_in_article("gear_name",["妈妈"])
    for x in m:
        list11.append(x)
    print(m)
    list11=m[:10]
    return render_template('gears/detail.html',gears = list11 )


@main.route("detail/<string:name>")
def getclass(name):
    name =  name.split("_")
    lis=[]
    print("================")
    for x in name:
        m = Gears.find_words_in_article("gear_class",[x,])
        lis.extend(m)
    return render_template('gears/detail.html',gears = lis )

web21/templates/gears/detail.html
<!DOCTYPE html>
<html lang="zh-CN"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=0.7">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>Parents on journey</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/blog.css" rel="stylesheet">
    <link href="/static/css/markdown.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
.en-markup-crop-options {
    top: 18px !important;
    left: 50% !important;
    margin-left: -100px !important;
    width: 200px !important;
    border: 2px rgba(255,255,255,.38) solid !important;
    border-radius: 4px !important;
}

.en-markup-crop-options div div:first-of-type {
    margin-left: 0px !important;
}
</style></head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="#">Home</a>
<!--
          <a class="blog-nav-item" href="#">关于本站</a>
          <a class="blog-nav-item" href="#">家庭旅行 tips</a>
          <a class="blog-nav-item" href="#">宝贝在路上</a>
          <a class="blog-nav-item" href="#">About</a>
-->
          
        </nav>
        
      </div>  
    </div>
    <div class="blog-masthead-pic"> </div>
    <div class="container">

      <div class="blog-header">
       
        <p class="lead blog-description">淘宝优惠检索系统.</p>
        
        
      </div>

      <div class="row">

        <div class="col-sm-12 blog-main">
          
          
      <div class="row">
        <div class="col-md-12">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th class="th_head">#</th>
                <th class="th_head">名称</th>
                <th class="th_head">单价</th>
				<th class="th_head">优惠条件</th>
                <th class="th_head">图片</th>
                <th class="th_head">佣金</th>
                <th class="th_head">分类</th>
<!--                <th class="th_head">推广</th>-->
                            
              </tr>
            </thead>
            <tbody>
             
           {%    for x in gears       %}

              <tr>
                <td class="td_index">{{x.id}}</td>
                <td class="td_name">          
                	<a class="td_in_name" href="{{x.tbk_url}}">{{x.gear_name}}</a>
				</td>
               
                <td class="td_price">{{x.gear_price}}元</td>
                <td class="td_return">
					<a class="td_in_link" href="{{x.coupon_tbk_link}}">优惠条件:<br>
               		{{x.coupon_detail}}</a>
                </td>
                <td class="td_pic">
                
					<a href="{{x.tbk_url}}" >
					<img class="td_in_pic" src="{{x.gear_pic}}">
					</a>
                	
                </td>

                <td class="td_url">
                	佣金: {{x.tbk_return}}元 <hr>
                	佣金比例: {{x.tbk_v_return}} %
                </td>
				<td class="td_return">
                	<a class="td_in_link" href="detail/{{x.gear_class | replace('/', '_') }}" >
					{{x.gear_class | replace('/', '_') }}
					</a>
                </td>
          
                
<!--
                <td class="td_return">
                	<a href="{{x.tbk_url}}" >
					推广链接
					</a>
                </td>
-->
          
              </tr>
            {% endfor    %}
           
              
              
            </tbody>
          </table>
        </div>
      </div>
      
      <!-- /.blog-post -->
        </div>
        
        
        <!-- /.blog-main -->

<!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>本网站由 <a href="http://getbootstrap.com/">Bootstrap</a> by <a href="https://www.zhihu.com/people/neromous">@neromous</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery.min.js"><\/script>')</script>
    <script src="/static/js/bootstrap.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
  

</body></html>

web21/templates/gears/index.html
<!DOCTYPE html>
<html lang="zh-CN"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=0.7">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>Parents on journey</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/blog.css" rel="stylesheet">
    <link href="/static/css/markdown.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
.en-markup-crop-options {
    top: 18px !important;
    left: 50% !important;
    margin-left: -100px !important;
    width: 200px !important;
    border: 2px rgba(255,255,255,.38) solid !important;
    border-radius: 4px !important;
}

.en-markup-crop-options div div:first-of-type {
    margin-left: 0px !important;
}
</style></head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="/">Home</a>
          <a class="blog-nav-item" href="#">关于本站</a>
          <a class="blog-nav-item" href="#">家庭旅行 tips</a>
          <a class="blog-nav-item" href="#">宝贝在路上</a>
          <a class="blog-nav-item" href="#">About</a>
        </nav>
        
      </div>  
    </div>
    <div class="blog-masthead-pic"> </div>
    <div class="container">

      <div class="blog-header">
       
        <p class="lead blog-description">淘宝优惠检索系统.</p>
        
        
      </div>

      <div class="row">

        <div class="col-sm-12 blog-main">
          
          
      <div class="row">
        <div class="col-md-8">

		  <form class="form-inline" action="{{url_for('gears.search')}}">
            <div class="form-group">
              <input class="form-control" type="text" name="searchtext" placeholder="请输入要搜索的商品">
            </div>

            <button class="btn btn-success" type="submit">搜索</button>
          </form>
     
     	</div>
      </div>
      
      <!-- /.blog-post -->
        </div>
        
        
        <!-- /.blog-main -->

<!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>本网站由 <a href="http://getbootstrap.com/">Bootstrap</a> by <a href="https://www.zhihu.com/people/neromous">@neromous</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery.min.js"><\/script>')</script>
    <script src="/static/js/bootstrap.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
  

</body></html>