web21/models/blog.py
from sqlalchemy import *
from models import Base,Model_action


class Blog(Base, Model_action):
    """
    Model 是所有 model 的基类
    @classmethod 是一个套路用法
    例如
    user = User()
    user.db_path() 返回 User.txt
    """
    def __init__(self):
        self.path = "sqlite:///data/article.sqlite"
        self.base = Base

    __tablename__ = "Blog"
    id = Column(Integer, primary_key=True)
    title = Column(String, default='')
    summary = Column(String, default='')
    img = Column(String, default='')
    subtitle = Column(String, default='')
    article = Column(String, default='')
    tags = Column(String, default='')
    srcid = Column(Integer, default='')

    #这个是关键的,不能包在外面

web21/routes/article.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

import time
import json
from utils import log
from routes import *
import pickle

from jieba import analyse
import jieba

from models.article import Article

main = Blueprint('article', __name__)


# @main.route("/")
# def index():
#     return render_template("blog/editor.html")


@main.route("/new")
def test1():
    return render_template("blog/editor_markdown.html")


@main.route("/add",methods=["POST"])
def add():
    form =  request.get_json()
    log('==============',form)
    Article().new(form)
    return redirect(url_for('.index'))


@main.route("/add/markdown",methods=["POST"])
def add_markdown():
    form = request.form
    log('==============', form)
    Article().new(form)
    return redirect(url_for('index.index'))


@main.route("/detail/<string:id>")
def detail(id):
    m = Article().find(id)
    log(m)
    return render_template("blog/detail.html",article = m)


@main.route("/del/<string:id>")
def delete(id):
    id = int(id)
    Article().delete(id)
    return redirect(url_for('.index'))

web21/templates/temp/blog/about.html
<!DOCTYPE html>
<html lang="zh-CN"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=0.7">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>Parents on journey</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/blog.css" rel="stylesheet">
    <link href="/static/css/markdown.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
.en-markup-crop-options {
    top: 18px !important;
    left: 50% !important;
    margin-left: -100px !important;
    width: 200px !important;
    border: 2px rgba(255,255,255,.38) solid !important;
    border-radius: 4px !important;
}

.en-markup-crop-options div div:first-of-type {
    margin-left: 0px !important;
}
</style></head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="#">Home</a>
          <a class="blog-nav-item" href="#">关于本站</a>
          <a class="blog-nav-item" href="#">家庭旅行 tips</a>
          <a class="blog-nav-item" href="#">宝贝在路上</a>
          <a class="blog-nav-item" href="#">About</a>
          
        </nav>
        
      </div>  
    </div>
    
    
    <div class="blog-masthead-pic">
    <img class="blog-main-img"  src="/static/img/2071.jpg">
    
	</div>
    <div class="container">

      <div class="blog-header">
       
        <p class="lead blog-description">同最爱的人一起发现更大的世界.</p>
        
        
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
          
          


          <div class="blog-post">
            <h2 class="blog-post-title">关于本站</h2>

            <p class="blog-post-meta"> by <a href="/about">旅途有家人</a></p>
            <hr>
<hr>
            <div class="post-article markdown-body">
            <h3> 本站是由yanping qin 以及 jing zhang 一起携手开办的网站</h3> <p>当然那个正在旁边一边看电视一边吃水果,主要技术工作均有jing zhang完成,稍后不日便会更新英文版,敬请期待, 未来本站会上传更多母婴及家庭哺育及教育相关的知识. </p>
            
            
            
            
            </div>
          </div><!-- /.blog-post -->



        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>  -和亲爱的家人一起发现更大的世界.</p>
          </div>
          <div class="sidebar-module">
            <h4>Top Posts & Pages</h4>
            {%  for b in Best  %}
            
            <ol class="list-unstyled">
              <li><a href="{{b.path}}">{{b.title}}</a></li>
            </ol>
            
            
            {%        endfor    %}
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">知乎</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
			  <li><a href="#"> 新浪微博 </a></li>
			  <li><a href="#"> 微信公众号 </a></li>


            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>本网站由 <a href="http://getbootstrap.com/">Bootstrap</a> by <a href="https://www.zhihu.com/people/neromous">@neromous</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery.min.js"><\/script>')</script>
    <script src="/static/js/bootstrap.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
  

</body></html>

web21/templates/temp/blog/detail.html
<!DOCTYPE html>
<html lang="zh-CN"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=0.7">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>Parents on journey</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/blog.css" rel="stylesheet">
    <link href="/static/css/markdown.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
.en-markup-crop-options {
    top: 18px !important;
    left: 50% !important;
    margin-left: -100px !important;
    width: 200px !important;
    border: 2px rgba(255,255,255,.38) solid !important;
    border-radius: 4px !important;
}

.en-markup-crop-options div div:first-of-type {
    margin-left: 0px !important;
}
</style></head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="#">Home</a>
          <a class="blog-nav-item" href="#">关于本站</a>
          <a class="blog-nav-item" href="#">家庭旅行 tips</a>
          <a class="blog-nav-item" href="#">宝贝在路上</a>
          <a class="blog-nav-item" href="#">About</a>
          
        </nav>
        
      </div>  
    </div>
    <div class="blog-masthead-pic"> </div>
    <div class="container">

      <div class="blog-header">
       
        <p class="lead blog-description">同最爱的人一起发现更大的世界.</p>
        
        
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
          
          



          <div class="blog-post">
            <h2 class="blog-post-title">{{article.title}}</h2>
            <a class="user_avatar" href="">
            <img class="in-post" src="{{article.src}}">
			</a>
           
            <p class="blog-post-meta">{{article.creat_time}} by <a href="#">旅途有家人</a></p>
            <hr>
            <p class="post-summary">{{article.summary}}</p>
            <hr>
            <div class="post-article markdown-body">
            	{{   article.article | markdown }}
            </div>
          </div><!-- /.blog-post -->



          <nav>
            <ul class="pager">
              <li><a href="/blog/before">Pre</a></li>
              <li><a href="/blog/main/1">1</a></li>
              <li><a href="/blog/main/2">2</a></li>
              <li><a href="/blog/main/3">3</a></li>
              <li><a href="/blog/main/4">4</a></li>     
              <li><a href="/blog/next">Next</a></li>
            </ul>
          </nav>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>  -和亲爱的家人一起发现更大的世界.</p>
          </div>
          <div class="sidebar-module">
            <h4>Top Posts & Pages</h4>
            {%  for b in Best  %}
            
            <ol class="list-unstyled">
              <li><a href="{{b.path}}">{{b.title}}</a></li>
            </ol>
            
            
            {%        endfor    %}
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">知乎</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
			  <li><a href="#"> 新浪微博 </a></li>
			  <li><a href="#"> 微信公众号 </a></li>


            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>本网站由 <a href="http://getbootstrap.com/">Bootstrap</a> by <a href="https://www.zhihu.com/people/neromous">@neromous</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery.min.js"><\/script>')</script>
    <script src="/static/js/bootstrap.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
  

</body></html>

web21/templates/temp/blog/editor.html
<!DOCTYPE html>
<!-- saved from url=(0043)http://www.bootcss.com/p/bootstrap-wysiwyg/ -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <title>站点编辑器</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="富文本编辑器">
    <meta name="description" content="富文本编辑器">

<!--    <link rel="apple-touch-icon" href="">-->
    <link rel="shortcut icon" href="http://mindmup.s3.amazonaws.com/lib/img/favicon.ico">
    <link href="/static/editor/prettify.css" rel="stylesheet">
    <link href="/static/editor/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="/static/editor/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="/static/editor/font-awesome.css" rel="stylesheet">
    <link href="/static/editor/index.css" rel="stylesheet">
    
  </head>
  <body>

<div class="container">
  <div class="hero-unit">
	<h3>站点编辑器 <br> <small>富文本编辑器,可以直接黏贴markdown文本进行输入</small></h3>
    <input class="blog-title" type="text"  style="width: 95%;" placeholder="请输入标题..." >
    	<div class="btn-toolbar" data-role="editor-toolbar" data-target="#editor">
      <div class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" title="" data-original-title="Font"><i class="icon-font"></i><b class="caret"></b></a>
          <ul class="dropdown-menu">
          <li><a data-edit="fontName Serif" style="font-family:&#39;Serif&#39;">Serif</a></li><li><a data-edit="fontName Sans" style="font-family:&#39;Sans&#39;">Sans</a></li><li><a data-edit="fontName Arial" style="font-family:&#39;Arial&#39;">Arial</a></li><li><a data-edit="fontName Arial Black" style="font-family:&#39;Arial Black&#39;">Arial Black</a></li><li><a data-edit="fontName Courier" style="font-family:&#39;Courier&#39;">Courier</a></li><li><a data-edit="fontName Courier New" style="font-family:&#39;Courier New&#39;">Courier New</a></li><li><a data-edit="fontName Comic Sans MS" style="font-family:&#39;Comic Sans MS&#39;">Comic Sans MS</a></li><li><a data-edit="fontName Helvetica" style="font-family:&#39;Helvetica&#39;">Helvetica</a></li><li><a data-edit="fontName Impact" style="font-family:&#39;Impact&#39;">Impact</a></li><li><a data-edit="fontName Lucida Grande" style="font-family:&#39;Lucida Grande&#39;">Lucida Grande</a></li><li><a data-edit="fontName Lucida Sans" style="font-family:&#39;Lucida Sans&#39;">Lucida Sans</a></li><li><a data-edit="fontName Tahoma" style="font-family:&#39;Tahoma&#39;">Tahoma</a></li><li><a data-edit="fontName Times" style="font-family:&#39;Times&#39;">Times</a></li><li><a data-edit="fontName Times New Roman" style="font-family:&#39;Times New Roman&#39;">Times New Roman</a></li><li><a data-edit="fontName Verdana" style="font-family:&#39;Verdana&#39;">Verdana</a></li></ul>
        </div>
      <div class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" title="" data-original-title="Font Size"><i class="icon-text-height"></i>&nbsp;<b class="caret"></b></a>
          <ul class="dropdown-menu">
          <li><a data-edit="fontSize 5"><font size="5">Huge</font></a></li>
          <li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
          <li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
          </ul>
      </div>
      <div class="btn-group">
        <a class="btn" data-edit="bold" title="" data-original-title="Bold (Ctrl/Cmd+B)"><i class="icon-bold"></i></a>
        <a class="btn" data-edit="italic" title="" data-original-title="Italic (Ctrl/Cmd+I)"><i class="icon-italic"></i></a>
        <a class="btn" data-edit="strikethrough" title="" data-original-title="Strikethrough"><i class="icon-strikethrough"></i></a>
        <a class="btn" data-edit="underline" title="" data-original-title="Underline (Ctrl/Cmd+U)"><i class="icon-underline"></i></a>
      </div>
      <div class="btn-group">
        <a class="btn" data-edit="insertunorderedlist" title="" data-original-title="Bullet list"><i class="icon-list-ul"></i></a>
        <a class="btn" data-edit="insertorderedlist" title="" data-original-title="Number list"><i class="icon-list-ol"></i></a>
        <a class="btn" data-edit="outdent" title="" data-original-title="Reduce indent (Shift+Tab)"><i class="icon-indent-left"></i></a>
        <a class="btn" data-edit="indent" title="" data-original-title="Indent (Tab)"><i class="icon-indent-right"></i></a>
      </div>
      <div class="btn-group">
        <a class="btn btn-info" data-edit="justifyleft" title="" data-original-title="Align Left (Ctrl/Cmd+L)"><i class="icon-align-left"></i></a>
        <a class="btn" data-edit="justifycenter" title="" data-original-title="Center (Ctrl/Cmd+E)"><i class="icon-align-center"></i></a>
        <a class="btn" data-edit="justifyright" title="" data-original-title="Align Right (Ctrl/Cmd+R)"><i class="icon-align-right"></i></a>
        <a class="btn" data-edit="justifyfull" title="" data-original-title="Justify (Ctrl/Cmd+J)"><i class="icon-align-justify"></i></a>
      </div>
      <div class="btn-group">
		  <a class="btn dropdown-toggle" data-toggle="dropdown" title="" data-original-title="Hyperlink"><i class="icon-link"></i></a>
		    <div class="dropdown-menu input-append">
			    <input class="span2" placeholder="URL" type="text" data-edit="createLink">
			    <button class="btn" type="button">Add</button>
        </div>
        <a class="btn" data-edit="unlink" title="" data-original-title="Remove Hyperlink"><i class="icon-cut"></i></a>

      </div>
      
      <div class="btn-group">
        <a class="btn" title="" id="pictureBtn" data-original-title="Insert picture (or just drag &amp; drop)"><i class="icon-picture"></i></a>
        <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" style="opacity: 0; position: absolute; top: 0px; left: 0px; width: 41px; height: 30px;">
      </div>
      <div class="btn-group">
        <a class="btn" data-edit="undo" title="" data-original-title="Undo (Ctrl/Cmd+Z)"><i class="icon-undo"></i></a>
        <a class="btn" data-edit="redo" title="" data-original-title="Redo (Ctrl/Cmd+Y)"><i class="icon-repeat"></i></a>
      </div>
      <input type="text" data-edit="inserttext" id="voiceBtn" x-webkit-speech="" style="display: none;">
    </div>
    	<div id="editor" class="wysiwyg"  name="content" contenteditable="true">
		  Go ahead…
		</div>
	   <button id="input" type="button" class="wysiwyg-btn btn btn-primary">提交</button>
	  </div>
</div>

<script src="/static/editor/jquery.min.js"></script>
<script src="/static/editor/jquery.hotkeys.js"></script>
<script src="/static/editor/bootstrap.min.js"></script>
<script src="/static/editor/bootstrap-wysiwyg.js"></script>
<script>
  $(function(){
    function initToolbarBootstrapBindings() {
      var fonts = ['Serif', 'Sans', 'Arial', 'Arial Black', 'Courier', 
            'Courier New', 'Comic Sans MS', 'Helvetica', 'Impact', 'Lucida Grande', 'Lucida Sans', 'Tahoma', 'Times',
            'Times New Roman', 'Verdana'],
            fontTarget = $('[title=Font]').siblings('.dropdown-menu');
      $.each(fonts, function (idx, fontName) {
          fontTarget.append($('<li><a data-edit="fontName ' + fontName +'" style="font-family:\''+ fontName +'\'">'+fontName + '</a></li>'));
      });
      $('a[title]').tooltip({container:'body'});
    	$('.dropdown-menu input').click(function() {return false;})
		    .change(function () {$(this).parent('.dropdown-menu').siblings('.dropdown-toggle').dropdown('toggle');})
        .keydown('esc', function () {this.value='';$(this).change();});

      $('[data-role=magic-overlay]').each(function () { 
        var overlay = $(this), target = $(overlay.data('target')); 
        overlay.css('opacity', 0).css('position', 'absolute').offset(target.offset()).width(target.outerWidth()).height(target.outerHeight());
      });
      $('#voiceBtn').hide();
      // if ("onwebkitspeechchange"  in document.createElement("input")) {
      //   var editorOffset = $('#editor').offset();
      //   $('#voiceBtn').css('position','absolute').offset({top: editorOffset.top, left: editorOffset.left+$('#editor').innerWidth()-35});
      // } else {
      //   $('#voiceBtn').hide();
      // }
    };
    initToolbarBootstrapBindings();  
    $('#editor').wysiwyg();
    window.prettyPrint && prettyPrint();
  });
</script>
        <script src="/static/gua.js"></script>
        <script src="/static/blog.js"></script>


<div id="fb-root"></div>
<script src="/static/editor/projects.js"></script>
<script src="/static/editor/h.js" type="text/javascript"></script>
<script src="/static/editor/h.js" type="text/javascript"></script>

</body></html>

web21/templates/temp/blog/editor_markdown.html
<!DOCTYPE html>
<!-- saved from url=(0043)http://www.bootcss.com/p/bootstrap-wysiwyg/ -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <title>站点编辑器</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="富文本编辑器">
    <meta name="description" content="富文本编辑器">

<!--    <link rel="apple-touch-icon" href="">-->
    <link rel="shortcut icon" href="http://mindmup.s3.amazonaws.com/lib/img/favicon.ico">
    <link href="/static/editor/prettify.css" rel="stylesheet">
    <link href="/static/editor/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="/static/editor/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="/static/editor/font-awesome.css" rel="stylesheet">
    <link href="/static/editor/index.css" rel="stylesheet">
    
  </head>
  <body>

<div class="container">
  <div class="hero-unit">
	<h3>站点编辑器 <br> <small>富文本编辑器,可以直接黏贴markdown文本进行输入</small></h3>
	<form id="create_topic_form" method="post" action="{{url_for('article.add_markdown') }}">
		<fieldset>
	<textarea autofocus class="span9" id="title"  name="title" rows="1" placeholder="标题字数 10 字以上" style="width: 90%;"></textarea>
    	<textarea autofocus class="span9" id=""  name="tags" rows="1" placeholder="标题字数 10 字以上" style="width: 20%;"></textarea>

			<textarea class="editor" name="article" rows="20"
					  placeholder="文章支持 Markdown 语法, 请注意标记代码" style="width: 90%;"></textarea>
			<div class="editor_buttons">
				<input type="submit" class="span-primary submit_btn" data-loading-text="提交中"
					   value="提交">
			</div>



                        </fieldset>
                    </form>
		</div>

	  </div>


<script src="/static/editor/jquery.min.js"></script>
<!--<script src="/static/editor/jquery.hotkeys.js"></script>-->
<script src="/static/editor/bootstrap.min.js"></script>
<!--<script src="/static/editor/bootstrap-wysiwyg.js"></script>-->

<!--        <script src="/static/gua.js"></script>-->
<!--        <script src="/static/blog.js"></script>-->


<div id="fb-root"></div>
<!--<script src="/static/editor/projects.js"></script>-->
<!--<script src="/static/editor/h.js" type="text/javascript"></script>-->
<!--<script src="/static/editor/h.js" type="text/javascript"></script>-->

</body></html>

web21/templates/temp/blog/update.html
<!DOCTYPE html>
<!-- saved from url=(0043)http://www.bootcss.com/p/bootstrap-wysiwyg/ -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <title>站点编辑器</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="富文本编辑器">
    <meta name="description" content="富文本编辑器">

<!--    <link rel="apple-touch-icon" href="">-->
    <link rel="shortcut icon" href="http://mindmup.s3.amazonaws.com/lib/img/favicon.ico">
    <link href="/static/editor/prettify.css" rel="stylesheet">
    <link href="/static/editor/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="/static/editor/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="/static/editor/font-awesome.css" rel="stylesheet">
    <link href="/static/editor/index.css" rel="stylesheet">
    
  </head>
  <body>

<div class="container">
  <div class="hero-unit">
	<h3>站点编辑器 <br> <small>富文本编辑器,可以直接黏贴markdown文本进行输入</small></h3>
	<form id="create_topic_form" method="post" action="{{url_for('article.add_markdown') }}">
		<fieldset>
      	<textarea autofocus class="span9" id="id"  name="id"  style="width: 90%;"></textarea>
	<textarea autofocus class="span9" id="title"  name="title" rows="1" placeholder="标题字数 10 字以上" style="width: 90%;"></textarea>
    	<textarea autofocus class="span9" id=""  name="tags" rows="1" placeholder="标题字数 10 字以上" style="width: 20%;"></textarea>

			<textarea class="editor" name="article" rows="20"
					  placeholder="文章支持 Markdown 语法, 请注意标记代码" style="width: 90%;"></textarea>
			<div class="editor_buttons">
				<input type="submit" class="span-primary submit_btn" data-loading-text="提交中"
					   value="提交">
			</div>



                        </fieldset>
                    </form>
		</div>

	  </div>


<script src="/static/editor/jquery.min.js"></script>
<!--<script src="/static/editor/jquery.hotkeys.js"></script>-->
<script src="/static/editor/bootstrap.min.js"></script>
<!--<script src="/static/editor/bootstrap-wysiwyg.js"></script>-->

<!--        <script src="/static/gua.js"></script>-->
<!--        <script src="/static/blog.js"></script>-->


<div id="fb-root"></div>
<!--<script src="/static/editor/projects.js"></script>-->
<!--<script src="/static/editor/h.js" type="text/javascript"></script>-->
<!--<script src="/static/editor/h.js" type="text/javascript"></script>-->

</body></html>